/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.github.fengshch.mybatis


//import spock.lang.Specification

/**
 * A simple unit test for the 'com.github.fengshch.mybatis.greeting' plugin.
 */
class MybatisPlusGradlePluginTest  {
//    def "plugin registers task"() {
//        given:
//        def project = ProjectBuilder.builder().build()
//
//        when:
//        project.plugins.apply("com.github.fengshch.mybatis.greeting")
//
//        then:
//        project.tasks.findByName("greeting") != null
//    }
}
